### ISSUE TITLE
So is it dead?

### ISSUE THREAD

**Issue by Nordomus** [simply-jos/penumbra_overture_vr#17]
Why won't you just say it's dead? Break in communication is the worst thing ever. We don't know if we should wait for it or not.

**Comment by handsomematt** [comment]
it's DONE

**Comment by Nordomus** [comment]
Wait what?

**Comment by veryjos** [comment]
I'm not working on it any more, but it's obviously right here on GitHub so anybody else can continue working on it :~)

I don't even have a Vive any more. I might pick up a Rift some time, though.
